import { Drill, DrillCategory, ShotType } from "@/types/drill";

export const MOCK_DRILLS: Drill[] = [
  {
    id: "1",
    name: "Closeout Box",
    categories: [DrillCategory.Defense],
    shot_density: 3.5,
    shot_type: ShotType.ThreePoint,
    intensity: 3,
    video_url: "",
  },
  {
    id: "2",
    name: "Ball Screen Coverage",
    categories: [DrillCategory.Defense],
    shot_density: 2.0,
    shot_type: ShotType.MidRange,
    intensity: 3,
    video_url: "",
  },
  {
    id: "3",
    name: "Horns Set — Elbow Iso",
    categories: [DrillCategory.Offense],
    shot_density: 1.5,
    shot_type: ShotType.MidRange,
    intensity: 2,
    video_url: "",
  },
  {
    id: "4",
    name: "3-on-2 Fast Break",
    categories: [DrillCategory.Transition],
    shot_density: 4.0,
    shot_type: ShotType.Finish,
    intensity: 3,
    video_url: "",
  },
  {
    id: "5",
    name: "Corner 3 Catch-and-Shoot",
    categories: [DrillCategory.Offense],
    shot_density: 5.0,
    shot_type: ShotType.ThreePoint,
    intensity: 2,
    video_url: "",
  },
  {
    id: "6",
    name: "Free Throw — Ice Pressure",
    categories: [DrillCategory.SpecialTeams],
    shot_density: 1.0,
    shot_type: ShotType.FreeThrow,
    intensity: 1,
    video_url: "",
  },
];
