import { Drill, DrillCategory, ShotType } from "@/types/drill";

export const MOCK_DRILLS: Drill[] = [
  {
    id: "1",
    name: "Closeout Box",
    category: DrillCategory.Defense,
    sub_category: "Closeouts",
    shot_density: 3.5,
    shot_type: ShotType.ThreePoint,
    intensity: 4,
    video_url: "",
  },
  {
    id: "2",
    name: "Ball Screen Coverage",
    category: DrillCategory.Defense,
    sub_category: "Ball Screens",
    shot_density: 2.0,
    shot_type: ShotType.MidRange,
    intensity: 3,
    video_url: "",
  },
  {
    id: "3",
    name: "Horns Set — Elbow Iso",
    category: DrillCategory.Offense,
    sub_category: "Half-Court Sets",
    shot_density: 1.5,
    shot_type: ShotType.MidRange,
    intensity: 2,
    video_url: "",
  },
  {
    id: "4",
    name: "3-on-2 Fast Break",
    category: DrillCategory.Transition,
    sub_category: "Numbers Advantage",
    shot_density: 4.0,
    shot_type: ShotType.Finish,
    intensity: 5,
    video_url: "",
  },
  {
    id: "5",
    name: "Corner 3 Catch-and-Shoot",
    category: DrillCategory.Offense,
    sub_category: "Spot-Up Shooting",
    shot_density: 5.0,
    shot_type: ShotType.ThreePoint,
    intensity: 2,
    video_url: "",
  },
  {
    id: "6",
    name: "Free Throw — Ice Pressure",
    category: DrillCategory.SpecialTeams,
    sub_category: "End of Game",
    shot_density: 1.0,
    shot_type: ShotType.FreeThrow,
    intensity: 1,
    video_url: "",
  },
];
